import { ServiceItem, PricingPlan, TeamMember, ProjectCaseStudy, Testimonial, FAQItem } from './types';

export const COMPANY_INFO = {
  name: "ProxyTech",
  legalName: "ProxyTech Software Solutions LLC",
  tagline: "High-Performance Software Engineering & Digital Scale",
  heroHeadline: "Engineered for Scale. Built for Impact.",
  heroSubheadline: "We design, architect, and deploy mission-critical web applications, mobile platforms, and AI-native software systems for ambitious startups and enterprise leaders.",
  email: "hello@proxytech.dev",
  phone: "+1 (888) 776-9983",
  address: "100 Montgomery St, Suite 1900, San Francisco, CA & Remote Worldwide",
  socials: {
    github: "https://github.com/proxytech-dev",
    linkedin: "https://linkedin.com/company/proxytech-solutions",
    twitter: "https://x.com/proxytech_dev",
    calendly: "https://calendly.com/proxytech/discovery",
  },
  stats: [
    { label: "Production Deployments", value: "140+", description: "Shipped across fintech, healthtech & SaaS" },
    { label: "Core API Uptime SLA", value: "99.98%", description: "Battle-tested cloud infrastructure" },
    { label: "Monthly Active API Calls", value: "48M+", description: "High-concurrency data pipelines" },
    { label: "Engineering Net Promoter", value: "94", description: "Average client satisfaction score" },
  ],
};

export const SERVICES: ServiceItem[] = [
  {
    id: "app-development",
    slug: "app-development",
    title: "App Development",
    shortDescription: "Native iOS, Android, and cross-platform Flutter/React Native applications engineered for zero-latency user experiences.",
    fullDescription: "From early consumer MVPs to high-scale enterprise field applications, we engineer native and hybrid mobile solutions with offline-first synchronization, rigorous security, and seamless app store compliance.",
    iconName: "Smartphone",
    tags: ["iOS & Swift", "Android & Kotlin", "React Native", "Flutter", "Offline Sync", "Biometric Auth"],
    problemsSolved: [
      "Sluggish hybrid apps suffering from frame drops and high memory usage",
      "Inconsistent UI and broken gestures between iOS and Android versions",
      "Unreliable data sync when users travel through weak signal environments",
      "App store rejections and complex compliance bottlenecks",
    ],
    deliverables: [
      "Native iOS & Android builds with automated TestFlight / Google Play deployment pipelines",
      "Unified design system translated into pixel-perfect mobile components",
      "Encrypted SQLite/WatermelonDB local persistence layer with background sync",
      "Push notification architecture via Firebase & Apple APNs",
      "Comprehensive telemetry, crash reporting, and user session monitoring",
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "SQLite", "Firebase", "RevenueCat"],
    timeline: "6 - 12 Weeks per Release Cycle",
    benefits: [
      "Up to 40% lower development overhead via robust shared cross-platform architectures",
      "Smooth 60/120fps fluid gesture response and native hardware integration",
      "100% store submission acceptance track record with full security hardening",
    ],
    faqs: [
      {
        question: "Should we build cross-platform (React Native/Flutter) or 100% native?",
        answer: "For 90% of business applications, modern React Native or Flutter delivers identical user experience to native at approximately half the code maintenance cost. We recommend native Swift/Kotlin when your product relies extensively on specialized Bluetooth LE peripherals, low-level DSP audio processing, or ARKit/ARCore intensive pipelines.",
      },
      {
        question: "Do you handle App Store and Google Play submissions?",
        answer: "Yes. We configure complete CI/CD pipelines (Fastlane / GitHub Actions) to automatically build, sign, and submit test builds to TestFlight and Google Play Internal tracks, guiding you all the way through public store verification.",
      },
    ],
  },
  {
    id: "web-development",
    slug: "web-development",
    title: "Web Development",
    shortDescription: "Ultra-fast Next.js, React, and TypeScript web applications engineered for sub-second page loads and extreme conversions.",
    fullDescription: "We engineer enterprise web applications, customer portals, and high-converting marketing engines. Using Next.js App Router, edge computing, and strict typing, we ensure your web presence is snappy, resilient, and SEO-dominant.",
    iconName: "Globe",
    tags: ["Next.js App Router", "TypeScript", "Tailwind CSS", "Edge Runtime", "Micro-frontends", "Server Components"],
    problemsSolved: [
      "Bloated legacy single-page applications with 4+ second initial load times",
      "Poor search engine indexing resulting from client-only rendered JavaScript",
      "Frequent production runtime bugs caused by untyped spaghetti code",
      "Difficulty scaling web infrastructure when traffic surges 10x",
    ],
    deliverables: [
      "Next.js App Router full-stack web application with optimized Server Components",
      "Dynamic open-graph generation, canonical tags, and schema markup",
      "Headless CMS integration (Sanity, Strapi, or Contentful) or custom database backends",
      "Automated Lighthouse 95+ Core Web Vitals optimization pipeline",
      "Production Docker containerization or direct Vercel / AWS Amplify deployment",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Node.js", "Vercel", "GraphQL", "PostgreSQL"],
    timeline: "4 - 10 Weeks",
    benefits: [
      "Sub-800ms First Contentful Paint across mobile and desktop devices",
      "Dramatic boost in organic search discovery and Core Web Vitals pass rates",
      "Type-safe client-server contracts that eliminate 95% of data parsing runtime bugs",
    ],
    faqs: [
      {
        question: "How do you ensure our web application is fast on mobile networks?",
        answer: "We leverage Next.js Server Components to stream HTML directly from edge nodes, lazy-load non-critical client modules, serve modern AVIF/WebP image assets with explicit dimensions, and eliminate redundant client JavaScript bundles.",
      },
      {
        question: "Can you migrate an existing React SPA or WordPress site to Next.js?",
        answer: "Absolutely. We specialize in zero-downtime incremental migrations, preserving existing SEO equity, 301 redirect mapping, and back-linking integrity.",
      },
    ],
  },
  {
    id: "ui-ux-design",
    slug: "ui-ux-design",
    title: "UI/UX Design & Design Systems",
    shortDescription: "High-fidelity product design, intuitive workflows, interactive Figma prototypes, and scalable multi-brand design systems.",
    fullDescription: "Great engineering fails when software is confusing to use. Our UI/UX team combines behavioral product research with sleek, modern visual design to create user experiences that feel natural, delightful, and focused on user activation.",
    iconName: "Palette",
    tags: ["Design Systems", "Figma Variables", "WCAG 2.1 AA", "Interactive Prototyping", "UX Audits", "Micro-interactions"],
    problemsSolved: [
      "High user onboarding churn and drop-offs during key checkout or setup funnels",
      "Cluttered interfaces that overwhelm technical and non-technical users alike",
      "Disconnected UI styles built by different teams lacking design governance",
      "Accessibility shortcomings that risk compliance fines and alienate users",
    ],
    deliverables: [
      "Complete Figma design library with auto-layout, tokens, and dark/light modes",
      "Clickable interactive prototypes for user testing and stakeholder presentations",
      "User journey maps, information architecture schematics, and wireframe flows",
      "Comprehensive design token documentation for frictionless engineering handoff",
      "Full WCAG 2.1 AA accessibility compliance audit",
    ],
    technologies: ["Figma", "Framer", "Tokens Studio", "Principle", "UserTesting", "Maze"],
    timeline: "3 - 8 Weeks",
    benefits: [
      "Up to 3x reduction in frontend engineering implementation time via design token parity",
      "Measurable increase in signup completion rates and user feature adoption",
      "Consistent, premium brand presence that instills institutional trust",
    ],
    faqs: [
      {
        question: "Do you supply production-ready Figma tokens for developers?",
        answer: "Yes. We structure Figma files using design tokens (colors, typography, spacing, elevations) that match your Tailwind CSS configuration 1:1, allowing developers to copy classes and token variables directly without guessing.",
      },
      {
        question: "Can we test prototypes with real users before coding begins?",
        answer: "Yes, we run usability test sessions using unmoderated Maze tests or moderated Zoom sessions to validate assumptions prior to writing a single line of backend logic.",
      },
    ],
  },
  {
    id: "seo",
    slug: "seo",
    title: "Technical SEO & Growth",
    shortDescription: "Data-backed organic growth strategies, programmatic search architectures, and exhaustive technical SEO infrastructure.",
    fullDescription: "We do not sell generic blog posts. We build programmatic SEO engines, optimize page speed architectures, implement structured JSON-LD schemas, and construct search foundations that turn high-intent organic queries into paying customers.",
    iconName: "Search",
    tags: ["Technical SEO", "Programmatic SEO", "JSON-LD Schemas", "Core Web Vitals", "Crawl Budget", "International Hreflang"],
    problemsSolved: [
      "Websites invisible on Google despite possessing superior products",
      "Crawl budget waste caused by indexing duplicate query parameters or orphaned URLs",
      "Loss of search rankings following careless CMS redesigns or domain moves",
      "Lack of programmatic landing pages to capture long-tail high-intent buyer searches",
    ],
    deliverables: [
      "Comprehensive technical audit resolving 4xx/5xx errors, canonical conflicts, and crawl traps",
      "Automated XML sitemaps, robots.txt directives, and dynamic Open Graph tag engines",
      "Custom JSON-LD schema implementation (Organization, Product, Service, FAQ, Breadcrumbs)",
      "Programmatic SEO architecture strategy designed to generate hundreds of indexed landing pages",
      "Monthly search visibility tracking and keyword cannibalization prevention reports",
    ],
    technologies: ["Google Search Console", "Ahrefs", "Screaming Frog", "Schema.org", "Semrush", "Next.js Metadata API"],
    timeline: "Ongoing or 4-Week Technical Overhaul",
    benefits: [
      "Sustainable organic customer acquisition pipeline with zero ongoing ad spend",
      "Protection against algorithmic volatility through clean semantic HTML structure",
      "Dominance in rich search snippet placements (SERP FAQs, Breadcrumbs, Star ratings)",
    ],
    faqs: [
      {
        question: "How is technical SEO different from standard content marketing?",
        answer: "Technical SEO ensures search engines can efficiently discover, render, understand, and index your application's content. Without technical SEO, even high-quality articles fail to rank due to indexing blockers, slow response times, or faulty canonical chains.",
      },
      {
        question: "How long before we see organic search traffic improvements?",
        answer: "Technical fixes (such as repairing canonical loops or robots.txt indexation blocks) often generate indexation updates within 2 to 4 weeks. Organic keyword authority typically compounds over a 3 to 6-month horizon.",
      },
    ],
  },
  {
    id: "digital-marketing",
    slug: "digital-marketing",
    title: "Digital Marketing & Performance",
    shortDescription: "High-ROI B2B customer acquisition, paid performance engineering, funnel optimization, and attribution modeling.",
    fullDescription: "Engineered growth for ambitious businesses. We align paid search, LinkedIn campaigns, conversion rate optimization (CRO), and behavioral analytics to ensure every marketing dollar yields measurable revenue.",
    iconName: "BarChart3",
    tags: ["B2B Demand Gen", "Paid Search & Meta", "CRO Funnels", "PostHog & Mixpanel", "Attribution Modeling", "Lead Enrichment"],
    problemsSolved: [
      "High ad spending with low-quality, untracked, or non-converting clicks",
      "Broken event tracking pipelines between Google Ads, Meta Pixel, and CRM systems",
      "Landing pages converting below industry benchmarks (< 2%)",
      "Inability to attribute which specific ad campaign generated closed enterprise revenue",
    ],
    deliverables: [
      "Multi-channel tracking architecture configured via Google Tag Manager & Server-Side CAPI",
      "High-converting landing page variants with automated A/B testing infrastructure",
      "Full CRM pipeline synchronization (HubSpot / Salesforce / Supabase)",
      "Ad creative design, copy experimentation matrix, and audience retargeting funnels",
      "Real-time executive performance dashboard monitoring CAC, LTV, and ROAS",
    ],
    technologies: ["Google Ads", "LinkedIn Campaign Manager", "PostHog", "Mixpanel", "Segment", "HubSpot", "Zapier"],
    timeline: "Sprint-based or Monthly Retainer",
    benefits: [
      "Elimination of blind ad spend through 100% verified server-side conversion tracking",
      "Lower Customer Acquisition Cost (CAC) through aggressive landing page testing",
      "Predictable pipeline generation for sales and product qualification teams",
    ],
    faqs: [
      {
        question: "Do you integrate tracking with our internal database and CRM?",
        answer: "Yes. We set up server-side conversion webhooks to push offline conversions back into ad platforms once leads become qualified paying clients, training ad algorithms on genuine revenue rather than cheap clicks.",
      },
      {
        question: "What is your typical monthly ad spend requirement?",
        answer: "We recommend a minimum paid media budget of $3,000 to $10,000/month to achieve statistical significance quickly, though our engineering-led CRO work can also be applied to organic traffic funnels alone.",
      },
    ],
  },
  {
    id: "software-development",
    slug: "software-development",
    title: "Software & SaaS Development",
    shortDescription: "Custom cloud architectures, high-throughput microservices, business automation engines, and scalable SaaS platforms.",
    fullDescription: "We build reliable, high-availability software platforms that power critical business processes. From multi-tenant SaaS platforms to automated business workflow engines and AI agent connectors, our code is tested, documented, and built to withstand scale.",
    iconName: "Cpu",
    tags: ["Multi-Tenant SaaS", "Cloud Microservices", "Supabase & Postgres", "Docker & K8s", "Stripe Billing", "AI Agent Tooling"],
    problemsSolved: [
      "Off-the-shelf software tools that cannot handle your unique business workflow",
      "Fragmented data silos forcing employees to manually copy-paste across tools",
      "Monolithic backends that lock up under high-volume concurrent database queries",
      "Security vulnerabilities and lack of SOC2 / GDPR compliant data isolation",
    ],
    deliverables: [
      "Complete multi-tenant SaaS architecture with role-based access control (RBAC)",
      "Scalable relational database schema with indexed queries and automated backups",
      "Integrated billing workflows (Stripe Checkout, customer portal, usage metering)",
      "Resilient background job queue architecture (BullMQ, Redis, or Celery)",
      "REST & GraphQL APIs accompanied by automated OpenAPI / Swagger documentation",
    ],
    technologies: ["Node.js / Bun", "Python / FastAPI", "PostgreSQL", "Supabase", "Redis", "Docker", "AWS", "Stripe"],
    timeline: "8 - 16 Weeks",
    benefits: [
      "Zero vendor lock-in with 100% intellectual property ownership transferred to you",
      "Scales seamlessly to tens of thousands of concurrent users with minimal cloud spend",
      "Automated CI/CD testing suites ensuring new feature releases never break production",
    ],
    faqs: [
      {
        question: "How do you handle multi-tenant data security?",
        answer: "We enforce PostgreSQL Row Level Security (RLS) policies and strict tenant isolation layers, guaranteeing that no organization can ever view, query, or mutate another organization's records even in the event of an application logic bug.",
      },
      {
        question: "Do we own the full source code and intellectual property?",
        answer: "Yes, 100%. Upon milestone sign-off, all Git repositories, cloud deployment credentials, documentation, and intellectual property belong exclusively to your business.",
      },
    ],
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    category: "Starter",
    tagline: "Ideal for early-stage startups and businesses launching their initial MVP or modernizing a single product.",
    monthlyPrice: 3450,
    yearlyPrice: 2850,
    popular: false,
    deliverables: [
      "1 Dedicated Senior Full-Stack Engineer",
      "Up to 80 Development Hours / Month",
      "Bi-Weekly Production Sprint Releases",
      "Next.js, React, or Mobile App development",
      "Basic Supabase / PostgreSQL Setup",
      "Source Code Ownership & GitHub Access",
      "Automated CI/CD Pipeline Configuration",
    ],
    support: "Async Slack Channel & Email (24h SLA)",
    revisions: "Unlimited Sprint Adjustments",
    developmentHours: "80 hrs / month",
    maintenanceIncluded: true,
    seoAuditIncluded: false,
    ctaText: "Start with Starter",
  },
  {
    id: "growth",
    name: "Growth",
    category: "Growth",
    tagline: "Accelerated development for scaling companies requiring continuous feature velocity and UI polish.",
    monthlyPrice: 5950,
    yearlyPrice: 4950,
    popular: true,
    deliverables: [
      "2 Senior Engineers (Full-Stack + Mobile / Frontend)",
      "Dedicated UI/UX Design Support (Figma)",
      "Up to 160 Development Hours / Month",
      "Weekly Production Sprint Releases",
      "Full Technical SEO & Performance Audit",
      "Stripe / Supabase / Auth & Database Systems",
      "Direct Slack/Discord Workspace Integration",
      "Weekly Architectural Strategy Calls",
    ],
    support: "Dedicated Slack Channel (4h Response SLA)",
    revisions: "Unlimited Revisions & Backlog Prioritization",
    developmentHours: "160 hrs / month",
    maintenanceIncluded: true,
    seoAuditIncluded: true,
    ctaText: "Accelerate with Growth",
  },
  {
    id: "business",
    name: "Business",
    category: "Business",
    tagline: "A full multidisciplinary product pod for established companies replacing or augmenting internal teams.",
    monthlyPrice: 9800,
    yearlyPrice: 8200,
    popular: false,
    deliverables: [
      "Full Product Pod: 3 Senior Engineers + 1 Lead UI/UX Designer + 1 PM",
      "Up to 280 Development Hours / Month",
      "Continuous Deployment & Staging Pipelines",
      "Advanced Cloud Microservices (AWS / Supabase)",
      "Comprehensive Security Hardening & Penetration Testing",
      "Full Multi-Tenant SaaS Architecture Support",
      "Conversion Rate Optimization & Analytics Setup",
      "Daily Standups & Sprint Planning",
    ],
    support: "Real-time Slack, Phone & Dedicated Project Manager",
    revisions: "Unlimited Real-Time Sprints",
    developmentHours: "280 hrs / month",
    maintenanceIncluded: true,
    seoAuditIncluded: true,
    ctaText: "Scale with Business Pod",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    category: "Enterprise",
    tagline: "Custom engineering SLAs, high-concurrency systems, legacy modernization, and 24/7 dedicated mission control.",
    monthlyPrice: "Custom",
    yearlyPrice: "Custom",
    popular: false,
    deliverables: [
      "Custom Scaled Engineering Squad (5+ Engineers & Architects)",
      "Dedicated Enterprise Solution Architect & Staff Security Engineer",
      "Guaranteed 99.99% Uptime SLA & 24/7/365 On-Call Emergency Pager",
      "SOC2 / HIPAA / GDPR Compliance Readiness Support",
      "Private VPC & Dedicated On-Premise Cloud Orchestration",
      "Custom Master Services Agreement (MSA) & Custom Invoicing",
      "Complete Knowledge Transfer & In-House Team Upskilling",
    ],
    support: "24/7 Dedicated Emergency Escalation + Dedicated VP",
    revisions: "Full Custom Agile Framework",
    developmentHours: "Custom / Dedicated Squad",
    maintenanceIncluded: true,
    seoAuditIncluded: true,
    ctaText: "Request Custom Proposal",
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "tariq-vance",
    slug: "tariq-vance",
    name: "Tariq Vance",
    role: "Founder & Chief Technology Architect",
    bio: "12+ years designing distributed web systems, high-scale database clusters, and cloud-native software architectures.",
    fullBio: "Tariq founded ProxyTech with a simple thesis: ambitious software companies need seasoned, hands-on senior engineers who understand business outcomes rather than junior agency bloat. He previously served as Principal Engineer at venture-backed cloud infrastructure startups, leading platforms handling over 100M monthly requests.",
    location: "San Francisco, CA (Remote Worldwide)",
    experienceYears: 12,
    skills: ["System Architecture", "PostgreSQL", "Next.js", "Distributed Systems", "Cloud Security", "Kubernetes"],
    socials: {
      github: "https://github.com/tariqvance",
      linkedin: "https://linkedin.com/in/tariq-vance",
      twitter: "https://x.com/tariqvance",
      email: "tariq@proxytech.dev",
    },
    projectsCount: 42,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "elena-rostova",
    slug: "elena-rostova",
    name: "Elena Rostova",
    role: "VP of Engineering & Cloud Systems",
    bio: "Specialist in edge compute runtimes, resilient microservices, and database performance optimization.",
    fullBio: "Elena oversees engineering execution and technical standards across all ProxyTech client deliveries. With a deep background in high-concurrency Node.js and Rust systems, she ensures that every system deployed by ProxyTech achieves sub-second latency and zero unexpected downtime.",
    location: "Austin, TX (Remote)",
    experienceYears: 10,
    skills: ["TypeScript", "Rust", "Node.js", "Docker", "Supabase", "Kafka", "Redis"],
    socials: {
      github: "https://github.com/erostova",
      linkedin: "https://linkedin.com/in/elena-rostova",
      twitter: "https://x.com/erostova_tech",
      email: "elena@proxytech.dev",
    },
    projectsCount: 38,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "marcus-chen",
    slug: "marcus-chen",
    name: "Marcus Chen",
    role: "Lead Full-Stack & Frontend Architect",
    bio: "Obsessed with Next.js App Router performance, React Server Components, and seamless user experiences.",
    fullBio: "Marcus leads ProxyTech's web engineering division. He turns complex business workflows into fluid, accessible, and blindingly fast web platforms. He is an active open-source contributor and speaker on modern React performance.",
    location: "Seattle, WA (Remote)",
    experienceYears: 8,
    skills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "GraphQL", "Web Vitals"],
    socials: {
      github: "https://github.com/marcuschen-dev",
      linkedin: "https://linkedin.com/in/marcus-chen",
      email: "marcus@proxytech.dev",
    },
    projectsCount: 31,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "sophia-almansoor",
    slug: "sophia-almansoor",
    name: "Sophia Al-Mansoor",
    role: "Lead UI/UX & Design Systems Director",
    bio: "Crafting minimalist, high-converting product interfaces and scalable design token architectures.",
    fullBio: "Sophia brings over 9 years of product design leadership from top Silicon Valley design consultancies. She bridges the gap between artistic elegance and engineering feasibility, ensuring every Figma component maps cleanly to production code.",
    location: "New York, NY (Remote)",
    experienceYears: 9,
    skills: ["Design Systems", "Figma", "User Research", "WCAG 2.1 AA", "Design Tokens", "Interaction Design"],
    socials: {
      linkedin: "https://linkedin.com/in/sophia-almansoor",
      twitter: "https://x.com/sophia_ui",
      email: "sophia@proxytech.dev",
    },
    projectsCount: 29,
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "david-kim",
    slug: "david-kim",
    name: "David Kim",
    role: "Mobile Applications Lead",
    bio: "Cross-platform mobile engineer specializing in Flutter, React Native, and offline-first data sync engines.",
    fullBio: "David has built and deployed mobile applications that have reached #1 in App Store productivity categories. At ProxyTech, he leads mobile initiatives ensuring unified UX across iOS and Android with strict hardware integration.",
    location: "Toronto, Canada (Remote)",
    experienceYears: 7,
    skills: ["React Native", "Flutter", "Swift", "Kotlin", "WatermelonDB", "App Store CI/CD"],
    socials: {
      github: "https://github.com/davidkim-mobile",
      linkedin: "https://linkedin.com/in/david-kim-eng",
      email: "david@proxytech.dev",
    },
    projectsCount: 26,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "amara-okafor",
    slug: "amara-okafor",
    name: "Amara Okafor",
    role: "Lead SEO & Search Growth Architect",
    bio: "Pioneering programmatic SEO pipelines, semantic schema graphs, and search indexation optimization.",
    fullBio: "Amara combines software engineering with organic search algorithms to build programmatic SEO systems that generate millions of monthly organic page impressions for B2B and SaaS clients.",
    location: "London, UK (Remote)",
    experienceYears: 8,
    skills: ["Technical SEO", "Programmatic SEO", "JSON-LD", "Data Analytics", "Information Retrieval"],
    socials: {
      linkedin: "https://linkedin.com/in/amara-okafor-seo",
      twitter: "https://x.com/amara_growth",
      email: "amara@proxytech.dev",
    },
    projectsCount: 24,
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=500&auto=format&fit=crop&q=80",
  },
];

export const PROJECTS: ProjectCaseStudy[] = [
  {
    id: "apex-fintech",
    slug: "apex-fintech-gateway",
    title: "ApexFlow Global Settlement Engine",
    tagline: "Sub-150ms cross-border multi-currency payment platform handling $180M+ annualized volume.",
    category: "SaaS",
    clientIndustry: "Financial Technology & B2B Payments",
    overview: "ApexFlow required an institutional-grade payment clearing portal and API gateway capable of processing instant ISO-20022 wire settlements while adhering to rigorous banking compliance.",
    challenge: "The client's legacy system experienced intermittent database lockups under high-concurrency webhook bursts, leading to delayed payment statuses and frustrated enterprise merchants.",
    solution: "ProxyTech re-architected the core payment dispatch using an asynchronous event pipeline backed by PostgreSQL Row-Level Security, Redis stream buffering, and a Next.js real-time merchant console.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Redis", "Supabase Auth", "Stripe API", "Tailwind CSS"],
    metrics: [
      { label: "API Latency Reduction", value: "-68%" },
      { label: "Peak Transaction Capacity", value: "3,400 req/s" },
      { label: "System Uptime Track Record", value: "99.99%" },
      { label: "Quarterly Volume Cleared", value: "$45M+" },
    ],
    timeline: "12 Weeks to Production",
    deliverables: [
      "Custom web dashboard with real-time WebSocket payment feeds",
      "Type-safe merchant SDK and interactive documentation",
      "Automated automated reconciliation engine with fraud triggers",
      "PCI-DSS Level 1 compliant data encryption pipeline",
    ],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: "zenith-health",
    slug: "zenith-health-mobile",
    title: "Zenith Care Telehealth & Remote Monitoring",
    tagline: "HIPAA-compliant cross-platform mobile app connecting 85,000+ patients to clinical care teams.",
    category: "Mobile App",
    clientIndustry: "Digital Health & Clinical Care",
    overview: "Zenith Health needed a modern mobile application providing secure video consultations, vital sign tracking via Bluetooth peripherals, and offline-accessible medical charts.",
    challenge: "Patients in rural regions frequently lost connection during video sessions, and battery consumption was too high due to unoptimized background BLE polling.",
    solution: "We engineered a battery-efficient React Native mobile app incorporating WebRTC fallback protocols and encrypted local SQLite storage, synchronizing asynchronously when connection returns.",
    technologies: ["React Native", "WebRTC", "TypeScript", "SQLite", "Node.js", "AWS HIPAA Cloud"],
    metrics: [
      { label: "App Store User Rating", value: "4.9 / 5.0" },
      { label: "Active Registered Patients", value: "85,000+" },
      { label: "Dropped Call Rate", value: "< 0.2%" },
      { label: "Battery Usage Reduction", value: "-42%" },
    ],
    timeline: "14 Weeks to App Store Launch",
    deliverables: [
      "iOS and Android store-ready application binaries",
      "Encrypted end-to-end messaging and HD video consultations",
      "Bluetooth LE integration with standard medical blood pressure cuffs",
      "Automated patient intake questionnaire with dynamic triage scoring",
    ],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: "omni-commerce",
    slug: "omni-commerce-headless",
    title: "Aura Headless Luxury Commerce & Design System",
    tagline: "Headless Next.js storefront delivering 320ms page loads and a +44% increase in checkout conversions.",
    category: "E-Commerce",
    clientIndustry: "Luxury Retail & Direct-to-Consumer",
    overview: "Aura wanted to replace a slow monolithic Shopify theme with a bespoke Next.js storefront backed by Algolia search and Shopify Storefront GraphQL APIs.",
    challenge: "Mobile bounce rates exceeded 62% due to 5.4-second load times on product category pages laden with heavy high-resolution media.",
    solution: "ProxyTech implemented Next.js App Router with incremental static regeneration (ISR), responsive AVIF media delivery, and an instant predictive search drawer.",
    technologies: ["Next.js", "Shopify GraphQL", "Tailwind CSS", "Algolia", "Framer Motion", "Vercel Edge"],
    metrics: [
      { label: "Mobile Bounce Rate", value: "-51%" },
      { label: "Checkout Conversion Rate", value: "+44%" },
      { label: "Google Lighthouse Score", value: "98 / 100" },
      { label: "Median Page Load Time", value: "320ms" },
    ],
    timeline: "8 Weeks",
    deliverables: [
      "Headless Next.js storefront with dynamic currency and localized pricing",
      "Custom Figma design system with matching React component library",
      "Integrated 1-click cart drawer and Apple Pay / Google Pay express flows",
      "Automated programmatic collection pages targeting 1,200+ long-tail search terms",
    ],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: "strata-automation",
    slug: "strata-ai-orchestration",
    title: "Strata Intelligence Enterprise Document Agent",
    tagline: "Automating 90,000 hours of manual enterprise invoice and legal contract extraction per month.",
    category: "AI & Automation",
    clientIndustry: "LegalTech & Enterprise Logistics",
    overview: "Strata needed a custom AI-driven workflow engine to ingest unstructured PDFs, extract line-item financial data with strict validation, and sync directly with SAP and Oracle ERPs.",
    challenge: "Off-the-shelf OCR solutions hallucinated on ambiguous scanned documents and lacked audit trails required by legal compliance.",
    solution: "We designed a multi-stage validation pipeline with human-in-the-loop review queues, vector search retrieval, and deterministic verification rules.",
    technologies: ["Python", "FastAPI", "Next.js", "PostgreSQL", "Supabase Storage", "OpenAI / Anthropic APIs"],
    metrics: [
      { label: "Extraction Accuracy Rate", value: "99.4%" },
      { label: "Document Processing Time", value: "1.8s avg" },
      { label: "Manual Review Reduction", value: "-88%" },
      { label: "Monthly Pages Ingested", value: "450,000+" },
    ],
    timeline: "10 Weeks",
    deliverables: [
      "Document ingestion portal with drag-and-drop batch upload",
      "Side-by-side verification UI with bounding box highlights",
      "Webhook and REST export pipelines into enterprise accounting systems",
      "Full role-based security access and cryptographic audit trail",
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    clientName: "Jonathan Reed",
    role: "Chief Technology Officer",
    company: "ApexFlow Payments",
    content: "ProxyTech is the most disciplined software agency we have ever worked with. They architected our core payment dispatch engine in 12 weeks, and we have experienced zero downtime since going live. Their code is clean, impeccably typed, and documented like an internal staff engineering team.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80",
    projectSlug: "apex-fintech-gateway",
  },
  {
    id: "test-2",
    clientName: "Dr. Sarah Lindqvist",
    role: "VP of Product",
    company: "Zenith Care Telehealth",
    content: "Our mobile app had critical performance and disconnect issues. ProxyTech overhauled our React Native architecture, rebuilt our WebRTC connection logic, and our rating leaped from 3.2 to 4.9 on the App Store. They don't just write code; they solve real business bottlenecks.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80",
    projectSlug: "zenith-health-mobile",
  },
  {
    id: "test-3",
    clientName: "Julian Vance-Moreau",
    role: "Founder & CEO",
    company: "Aura Luxury Retail",
    content: "Moving our storefront to Next.js with ProxyTech was the single best digital investment we made this year. Our mobile page speed dropped from 5+ seconds to 320ms, and our conversion rate jumped by 44% in the first 30 days. Their design system and token structure are world-class.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    projectSlug: "omni-commerce-headless",
  },
];

export const FAQS: FAQItem[] = [
  {
    id: "faq-1",
    question: "How does ProxyTech differ from typical digital agencies or freelancers?",
    answer: "Unlike traditional agencies that assign junior developers or outsource work overseas, ProxyTech assigns dedicated senior engineers and architects directly to your codebase. You communicate directly via shared Slack channels, participate in sprint demos, and receive production-grade code with automated tests and zero vendor lock-in.",
  },
  {
    id: "faq-2",
    question: "Who owns the code and intellectual property we build together?",
    answer: "You do. 100%. From the moment code is pushed to your Git repository, your company retains full ownership of all intellectual property, design assets, and cloud deployment configurations.",
  },
  {
    id: "faq-3",
    question: "What is your typical project kickoff timeline?",
    answer: "Following our initial 15-minute technical discovery call and scope alignment, we typically provision staging environments, invite your team to Slack/GitHub, and commence the first development sprint within 3 to 5 business days.",
  },
  {
    id: "faq-4",
    question: "Can we adjust sprint priorities or pause an ongoing plan?",
    answer: "Yes. Our monthly and yearly engagement models operate with agile flexibility. You can shift priorities between sprints, swap feature backlogs, or scale developer headcount up or down with a standard 14-day notice.",
  },
  {
    id: "faq-5",
    question: "Do you provide ongoing maintenance and post-launch support?",
    answer: "Every production build includes post-launch monitoring, security patch updates, dependency management, and guaranteed SLA response times to keep your software running smoothly at scale.",
  },
  {
    id: "faq-6",
    question: "Can your team integrate with our existing backend or internal engineering team?",
    answer: "Yes. Roughly half of our engagements involve augmenting existing technical teams. We seamlessly adapt to your established Git workflows, Jira/Linear sprint boards, and code review guidelines.",
  },
];

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Discovery & Architecture",
    description: "We map out your business objectives, review technical constraints, define database schemas, and create a comprehensive technical roadmap with zero ambiguity.",
  },
  {
    step: "02",
    title: "Sprint Delivery & Prototyping",
    description: "Rapid, test-driven development delivered in 1-2 week sprints. You see functional builds, review interactive PR previews, and test live staging software regularly.",
  },
  {
    step: "03",
    title: "QA, Security & Performance Hardening",
    description: "Rigorous end-to-end testing, Core Web Vitals optimization, automated security audits, and load stress testing to ensure rock-solid production readiness.",
  },
  {
    step: "04",
    title: "Production Launch & Continuous Scale",
    description: "Seamless deployment to Vercel/AWS, DNS cutover, telemetry monitoring setup, and ongoing proactive maintenance as your user base expands.",
  },
];

export const TECH_STACK_CHIPS = [
  "Next.js App Router", "TypeScript", "React 19", "Tailwind CSS",
  "PostgreSQL", "Supabase", "Node.js", "Python / FastAPI",
  "React Native", "Flutter", "Swift", "Kotlin",
  "Docker", "AWS Cloud", "Redis", "Figma Design Systems",
  "Stripe Billing", "GraphQL", "WebRTC", "OpenAI / Claude Tooling",
  "Vercel Edge", "Git CI/CD",
];
